import type { Generated } from 'kysely';

/**
 * Row shape for the `Agent` table.
 *
 * Agents are the actors who create / mutate everything else in the system
 * (memories, notes, milestones, …). Row id `0` is the immutable `none`
 * sentinel — every elevated entity FK-references an agent, and operations
 * with no human attribution point at id `0` rather than `NULL`.
 *
 * `agent_id`, `created_at`, and `updated_at` are filled by Postgres
 * (`GENERATED BY DEFAULT AS IDENTITY` and `DEFAULT NOW()`), so they're
 * wrapped with `Generated<T>` to let Kysely omit them on insert.
 *
 * @example
 * ```typescript
 * const row = await ctx.kysely
 *     .selectFrom('Agent')
 *     .selectAll()
 *     .where('agent_id', '=', 1)
 *     .executeTakeFirst();
 * ```
 */
export interface AgentRow {
    agent_id:    Generated<number>;
    name:        string;
    description: string;
    created_at:  Generated<Date>;
    updated_at:  Generated<Date>;
}

/**
 * Stored-procedure contract for the `Agent` domain.
 *
 * Each entry is a `[args, result]` tuple. Arg keys use snake_case to
 * mirror the Postgres parameter names (with the `p_` prefix dropped) —
 * the camelCase → snake_case mapping happens inside `AgentCommands`.
 *
 * - `sp_Agent_Create` returns the new `agent_id`.
 * - `sp_Agent_Update` and `sp_Agent_Delete` return nothing; the proc
 *   either succeeds or raises (sentinel-id guards live in SQL).
 *
 * @example
 * ```typescript
 * const { agent_id } = await ctx.proc('sp_Agent_Create', {
 *     name: 'claude-opus-4-7',
 *     description: 'authoring assistant',
 * });
 * ```
 */
export interface AgentProcs {
    'sp_Agent_Create': [
        {
            p_name: string;
            p_description: string;
        },
        { agent_id: number },
    ];
    'sp_Agent_Update': [
        {
            p_agent_id: number;
            p_name: string;
            p_description: string;
        },
        void,
    ];
    'sp_Agent_Delete': [
        { p_agent_id: number },
        void,
    ];
}
