import type { Generated } from 'kysely';

/**
 * Row shape for the `Tag` table.
 *
 * Tags are an *inclusive* subtype: one Tag can be attached to many entity
 * kinds simultaneously (Project, Memory, Artifact, Milestone, Task) via the
 * five `*_Tag` join tables. Tags have no `relevance_status` column —
 * deletion is hard, and FK `ON DELETE CASCADE` removes the join rows.
 *
 * `color` was added by the `2026-05-10-add-memory-tag-color` change as a
 * VARCHAR(16) defaulted to `''` (purely a UI/visualization affordance —
 * no semantic meaning, no validation in SQL beyond the length cap).
 *
 * `tag_id`, `created_at`, and `updated_at` are filled by Postgres
 * (`GENERATED BY DEFAULT AS IDENTITY` / `DEFAULT NOW()`); `color` defaults
 * to `''` server-side. All four are wrapped with `Generated<T>` so
 * Kysely lets callers omit them on insert.
 *
 * @example
 * ```typescript
 * const row = await ctx.kysely
 *     .selectFrom('Tag')
 *     .selectAll()
 *     .where('tag_id', '=', 1)
 *     .executeTakeFirst();
 * ```
 */
export interface TagRow {
    tag_id:        Generated<number>;
    provenance_id: number;
    agent_id:      number;
    name:          string;
    description:   string;
    reason:        string;
    color:         Generated<string>;
    created_at:    Generated<Date>;
    updated_at:    Generated<Date>;
}

/**
 * Stored-procedure contract for the `Tag` domain.
 *
 * Fourteen entries: Create, Update, Delete, Merge, plus five Attach / five
 * Detach pairs (one per attachable entity kind). Argument keys are
 * snake_case to mirror the PostgreSQL parameter names with the `p_` prefix
 * dropped — the camelCase → snake_case mapping happens inside `TagCommands`.
 *
 * Only `sp_Tag_Create` returns data (`{ tag_id }`). Everything else
 * (including Merge, which calls Delete internally) returns `void`.
 *
 * @example
 * ```typescript
 * const { tag_id } = await ctx.proc('sp_Tag_Create', {
 *     name: 'backend-performance', description: '', reason: '',
 *     provenance_id: 1, agent_id: 1,
 * });
 * await ctx.proc('sp_Tag_Attach_Memory', { tag_id, memory_id: 42 });
 * ```
 */
export interface TagProcs {
    'sp_Tag_Create': [
        {
            p_name:          string;
            p_description:   string;
            p_reason:        string;
            p_provenance_id: number;
            p_agent_id:      number;
        },
        { tag_id: number },
    ];
    'sp_Tag_Update': [
        {
            p_tag_id:      number;
            p_name:        string;
            p_description: string;
            p_reason:      string;
        },
        void,
    ];
    'sp_Tag_Delete': [
        { p_tag_id: number },
        void,
    ];
    'sp_Tag_Attach_Project': [
        { p_tag_id: number; p_project_id: number },
        void,
    ];
    'sp_Tag_Detach_Project': [
        { p_tag_id: number; p_project_id: number },
        void,
    ];
    'sp_Tag_Attach_Memory': [
        { p_tag_id: number; p_memory_id: number },
        void,
    ];
    'sp_Tag_Detach_Memory': [
        { p_tag_id: number; p_memory_id: number },
        void,
    ];
    'sp_Tag_Attach_Artifact': [
        { p_tag_id: number; p_artifact_id: number },
        void,
    ];
    'sp_Tag_Detach_Artifact': [
        { p_tag_id: number; p_artifact_id: number },
        void,
    ];
    'sp_Tag_Attach_Milestone': [
        { p_tag_id: number; p_milestone_id: number },
        void,
    ];
    'sp_Tag_Detach_Milestone': [
        { p_tag_id: number; p_milestone_id: number },
        void,
    ];
    'sp_Tag_Attach_Task': [
        { p_tag_id: number; p_milestone_id: number; p_task_no: number },
        void,
    ];
    'sp_Tag_Detach_Task': [
        { p_tag_id: number; p_milestone_id: number; p_task_no: number },
        void,
    ];
    'sp_Tag_Merge': [
        {
            p_source_tag_id: number;
            p_target_tag_id: number;
            p_agent_id:      number;
            p_reason:        string;
        },
        void,
    ];
}
