/**
 * Row + proc/func contracts for the Task domain.
 *
 * Task is a hierarchic child of Milestone with a composite PK
 * (milestone_id, task_no). It carries its own tracking state machine
 * and three binary facts: Task_Tag, Task_Artifact, Task_Dependency.
 * Task has no relevance_status — soft-delete is modelled as a
 * tracking transition to 'abandoned'. The Task_StateTransition
 * subtype audits every tracking move.
 */
import type { Generated } from 'kysely';

import type { TvpValue } from '@noormdev/sdk';

/**
 * Physical Task table row. (milestone_id, task_no) is the composite PK;
 * task_no is generated by fn_NextTaskNo inside sp_Task_Create. agent_id
 * defaults to the sentinel Agent(0); title/content/reason default to ''.
 */
export interface TaskRow {
    milestone_id: number;
    task_no: Generated<number>;
    tracking_status: string;
    agent_id: Generated<number>;
    title: Generated<string>;
    content: Generated<string>;
    reason: Generated<string>;
    created_at: Generated<Date>;
    updated_at: Generated<Date>;
}

/**
 * Subtype row joining a StateTransition (state_transition_type =
 * 'task-tracking') to its owning Task. The discriminator is enforced
 * by a CHECK constraint that calls fn_StateTransitionIsOfType.
 */
export interface TaskStateTransitionRow {
    transition_id: number;
    milestone_id: number;
    task_no: number;
    created_at: Generated<Date>;
}

/** Tag-to-Task binary fact. Composite PK (tag_id, milestone_id, task_no). */
export interface TaskTagRow {
    tag_id: number;
    milestone_id: number;
    task_no: number;
    created_at: Generated<Date>;
}

/**
 * Directed Task-to-Task dependency edge. The dependency_verb scopes
 * the relationship (e.g. 'blocks', 'relates-to') and is validated
 * against the DependencyVerb reference table by the proc layer.
 */
export interface TaskDependencyRow {
    milestone_id: number;
    task_no: number;
    dep_milestone_id: number;
    dep_task_no: number;
    dependency_verb: string;
    reason: Generated<string>;
    created_at: Generated<Date>;
}

/**
 * vw_Task_Backlog shape — open tasks under active Milestones plus a
 * computed is_blocked flag (BIT surfaced as boolean) that's true when
 * any outgoing 'blocks' edge targets a non-done task.
 */
export interface TaskBacklogView {
    milestone_id: number;
    task_no: number;
    title: string;
    content: string;
    tracking_status: string;
    agent_id: number;
    is_blocked: boolean;
    created_at: Date;
    updated_at: Date;
}

/**
 * Stored procedure contracts owned by the Task domain.
 *
 * Four base procs (Create / Update / SetTracking / Delete) plus the
 * dependency edge pair (Depend / Undepend) and the bulk Depend variant
 * that takes a TaskDependencyInput TVP for batched edge insertion.
 */
export interface TaskProcs {

    'sp_Task_Create': [
        {
            milestone_id: number;
            title: string;
            content?: string;
            reason?: string;
            agent_id?: number;
        },
        { milestone_id: number; task_no: number },
    ];

    'sp_Task_Update': [
        {
            milestone_id: number;
            task_no: number;
            title: string;
            content?: string;
            reason?: string;
        },
        void,
    ];

    'sp_Task_SetTracking': [
        {
            milestone_id: number;
            task_no: number;
            new_tracking_status: string;
            agent_id: number;
            reason?: string;
        },
        void,
    ];

    'sp_Task_Delete': [
        {
            milestone_id: number;
            task_no: number;
            agent_id: number;
            reason?: string;
        },
        void,
    ];

    'sp_Task_Depend': [
        {
            milestone_id: number;
            task_no: number;
            dep_milestone_id: number;
            dep_task_no: number;
            dependency_verb: string;
            reason?: string;
        },
        void,
    ];

    'sp_Task_Undepend': [
        {
            milestone_id: number;
            task_no: number;
            dep_milestone_id: number;
            dep_task_no: number;
        },
        void,
    ];

    'sp_Task_Bulk_Depend': [
        { Deps: TvpValue },
        void,
    ];

}

/**
 * Scalar function contracts owned by the Task domain.
 *
 * fn_NextTaskNo returns the next task_no for a given milestone (used
 * by sp_Task_Create internally; exposed for callers that need to
 * pre-allocate). fn_TaskDependencyWouldCycle returns a BIT (surfaced
 * as boolean or 0/1 depending on the driver) indicating whether the
 * proposed edge would close a cycle in the current dependency graph.
 */
export interface TaskFuncs {

    'fn_NextTaskNo': [
        { milestone_id: number },
        { next: number },
    ];

    'fn_TaskDependencyWouldCycle': [
        {
            milestone_id: number;
            task_no: number;
            dep_milestone_id: number;
            dep_task_no: number;
        },
        { cycles: boolean | number },
    ];

}
