/**
 * Checksum verification for binary release assets.
 *
 * Ports the pattern from the sibling `ignatius` repo but hardens its one
 * weakness: an unreachable/missing checksums.txt is a hard failure by
 * default (opt out via `insecure`), and a confirmed hash mismatch is ALWAYS
 * a hard failure — `insecure` can only ever downgrade "we couldn't prove
 * anything either way" to a warning, never "we proved this binary is bad".
 */
import { attempt } from '@logosdx/utils';

/**
 * Parse a `shasum -a 256`-style checksums file into an asset → sha256 map.
 *
 * Mirrors the exact output format the release workflow produces: a 64-char
 * hex hash, whitespace, an optional `*` binary-mode marker, then the
 * filename. checksums.txt is generated by a trusted CI step, not user
 * input — blank/malformed lines are skipped rather than thrown on, since a
 * single stray line shouldn't take down verification for every other entry.
 *
 * @example
 * const map = parseChecksums('deadbeef...  noorm-darwin-arm64\n');
 * map['noorm-darwin-arm64']; // 'deadbeef...'
 */
export function parseChecksums(text: string): Record<string, string> {

    const out: Record<string, string> = {};

    for (const line of text.split('\n')) {

        const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/i);

        if (match && match[1] && match[2]) {

            out[match[2]] = match[1].toLowerCase();

        }

    }

    return out;

}

/**
 * Compute the sha256 hex digest of a file on disk.
 *
 * Streams the file rather than buffering it whole — release binaries run
 * tens of MB, and buffering the full file would spike memory on every
 * update check for no benefit.
 *
 * @example
 * const hash = await sha256File('/tmp/noorm.download');
 */
export async function sha256File(path: string): Promise<string> {

    const hasher = new Bun.CryptoHasher('sha256');

    for await (const chunk of Bun.file(path).stream()) {

        hasher.update(chunk);

    }

    return hasher.digest('hex');

}

/**
 * A checksum verification failure.
 *
 * `reason` distinguishes two categorically different failures so callers
 * (and the `insecure` escape hatch) branch on structure instead of matching
 * error message text:
 * - `'unreachable'`: checksums.txt couldn't be fetched, or was fetched but
 *   didn't mention this asset. Either way we have no trustworthy answer —
 *   bypassable via `insecure`, the documented escape hatch for offline
 *   installs and mirrors without a checksums.txt.
 * - `'mismatch'`: checksums.txt was fetched and DID have an entry for this
 *   asset, and the computed hash disagrees with it. We have proof the bytes
 *   are wrong — never bypassable, by design (see `verifyChecksum`).
 */
export class ChecksumError extends Error {

    override readonly name = 'ChecksumError' as const;

    constructor(message: string, readonly reason: 'unreachable' | 'mismatch') {

        super(message);

    }

}

/**
 * Verify a downloaded file's sha256 against a release's checksums.txt.
 *
 * Security-critical asymmetry, deliberate: "we couldn't verify" (checksums.txt
 * unreachable, or missing an entry for this asset) is bypassable via
 * `insecure`. "We verified and it's wrong" is NEVER bypassable — `insecure`
 * only ever waves through the absence of proof, not a proven-bad binary.
 * Get this branch order wrong and the entire feature becomes a no-op for the
 * one case it exists to catch.
 *
 * @throws ChecksumError('mismatch') when the computed hash disagrees with a
 * found checksums.txt entry — unconditional, `insecure` has no effect here.
 * @throws ChecksumError('unreachable') when checksums.txt can't be fetched,
 * or has no entry for `assetName`, and `insecure` is false.
 *
 * @example
 * await verifyChecksum({
 *     checksumsUrl: getChecksumsUrl(version),
 *     assetName: getBinaryAssetName(),
 *     filePath: tmpPath,
 *     insecure: false,
 * });
 */
export async function verifyChecksum(opts: {
    checksumsUrl: string;
    assetName: string;
    filePath: string;
    insecure: boolean;
}): Promise<void> {

    const { checksumsUrl, assetName, filePath, insecure } = opts;

    const [response, fetchErr] = await attempt(() => fetch(checksumsUrl));

    if (fetchErr || !response || !response.ok) {

        if (insecure) return;

        throw new ChecksumError(`checksums.txt unreachable at ${checksumsUrl}`, 'unreachable');

    }

    const text = await response.text();
    const expected = parseChecksums(text)[assetName];

    if (!expected) {

        if (insecure) return;

        throw new ChecksumError(`no checksum entry for ${assetName} in ${checksumsUrl}`, 'unreachable');

    }

    const actual = await sha256File(filePath);

    if (actual !== expected) {

        throw new ChecksumError(
            `checksum mismatch for ${assetName} (expected ${expected}, got ${actual})`,
            'mismatch',
        );

    }

}
