-- Elevated entity: Agent
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Agent" (
    agent_id            INT GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(255) NOT NULL DEFAULT '',
    description         VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_agent PRIMARY KEY (agent_id)
);
