-- Elevated entity: Project
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Project" (
    project_id          INT GENERATED BY DEFAULT AS IDENTITY,
    agent_id            INT NOT NULL,
    name                VARCHAR(255) NOT NULL DEFAULT '',
    filepath            VARCHAR(255) NOT NULL DEFAULT '',
    git_repo            VARCHAR(255) NOT NULL DEFAULT '',
    main_branch         VARCHAR(255) NOT NULL DEFAULT '',
    git_url             VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_project PRIMARY KEY (project_id),
    CONSTRAINT fk_project_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_project_agent_id ON "Project" (agent_id);
