-- Elevated entity: Note
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Note" (
    note_id             INT GENERATED BY DEFAULT AS IDENTITY,
    note_type           VARCHAR(32) NOT NULL,
    relevance_status    VARCHAR(32) NOT NULL,
    provenance_id       INT NOT NULL,
    agent_id            INT NOT NULL,
    content             TEXT NOT NULL DEFAULT '',
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_note PRIMARY KEY (note_id),
    CONSTRAINT fk_note_note_type FOREIGN KEY (note_type) REFERENCES "NoteType"(note_type) ON DELETE RESTRICT,
    CONSTRAINT fk_note_relevance_status FOREIGN KEY (relevance_status) REFERENCES "RelevanceStatus"(relevance_status) ON DELETE RESTRICT,
    CONSTRAINT fk_note_provenance_id FOREIGN KEY (provenance_id) REFERENCES "Project"(project_id) ON DELETE RESTRICT,
    CONSTRAINT fk_note_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_note_note_type ON "Note" (note_type);
CREATE INDEX IF NOT EXISTS idx_note_relevance_status ON "Note" (relevance_status);
CREATE INDEX IF NOT EXISTS idx_note_provenance_id ON "Note" (provenance_id);
CREATE INDEX IF NOT EXISTS idx_note_agent_id ON "Note" (agent_id);
