-- Elevated entity: Tag
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Tag" (
    tag_id              INT GENERATED BY DEFAULT AS IDENTITY,
    provenance_id       INT NOT NULL,
    agent_id            INT NOT NULL,
    name                VARCHAR(255) NOT NULL UNIQUE,
    description         VARCHAR(255) NOT NULL DEFAULT '',
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_tag PRIMARY KEY (tag_id),
    CONSTRAINT fk_tag_provenance_id FOREIGN KEY (provenance_id) REFERENCES "Project"(project_id) ON DELETE RESTRICT,
    CONSTRAINT fk_tag_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_tag_provenance_id ON "Tag" (provenance_id);
CREATE INDEX IF NOT EXISTS idx_tag_agent_id ON "Tag" (agent_id);
