-- Elevated entity: Memory
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Memory" (
    memory_id           INT GENERATED BY DEFAULT AS IDENTITY,
    domain              VARCHAR(32) NOT NULL,
    category            VARCHAR(32) NOT NULL,
    relevance_status    VARCHAR(32) NOT NULL,
    provenance_id       INT NOT NULL,
    agent_id            INT NOT NULL,
    content             TEXT NOT NULL DEFAULT '',
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    was_inferred        BOOLEAN NOT NULL DEFAULT false,
    was_observed        BOOLEAN NOT NULL DEFAULT false,
    was_evidenced       BOOLEAN NOT NULL DEFAULT false,
    was_user_provided   BOOLEAN NOT NULL DEFAULT false,
    last_accessed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    access_count        INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_memory PRIMARY KEY (memory_id),
    CONSTRAINT fk_memory_domain FOREIGN KEY (domain) REFERENCES "MemoryDomain"(domain) ON DELETE RESTRICT,
    CONSTRAINT fk_memory_category FOREIGN KEY (category) REFERENCES "MemoryCategory"(category) ON DELETE RESTRICT,
    CONSTRAINT fk_memory_relevance_status FOREIGN KEY (relevance_status) REFERENCES "RelevanceStatus"(relevance_status) ON DELETE RESTRICT,
    CONSTRAINT fk_memory_provenance_id FOREIGN KEY (provenance_id) REFERENCES "Project"(project_id) ON DELETE RESTRICT,
    CONSTRAINT fk_memory_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_memory_domain ON "Memory" (domain);
CREATE INDEX IF NOT EXISTS idx_memory_category ON "Memory" (category);
CREATE INDEX IF NOT EXISTS idx_memory_relevance_status ON "Memory" (relevance_status);
CREATE INDEX IF NOT EXISTS idx_memory_provenance_id ON "Memory" (provenance_id);
CREATE INDEX IF NOT EXISTS idx_memory_agent_id ON "Memory" (agent_id);
CREATE INDEX IF NOT EXISTS idx_memory_last_accessed_at ON "Memory" (last_accessed_at);
