-- Elevated entity: Artifact
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Artifact" (
    artifact_id         INT GENERATED BY DEFAULT AS IDENTITY,
    relevance_status    VARCHAR(32) NOT NULL,
    provenance_id       INT NOT NULL,
    agent_id            INT NOT NULL,
    title               VARCHAR(255) NOT NULL DEFAULT '',
    description         VARCHAR(255) NOT NULL DEFAULT '',
    filepath            VARCHAR(255) NOT NULL DEFAULT '',
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_artifact PRIMARY KEY (artifact_id),
    CONSTRAINT fk_artifact_relevance_status FOREIGN KEY (relevance_status) REFERENCES "RelevanceStatus"(relevance_status) ON DELETE RESTRICT,
    CONSTRAINT fk_artifact_provenance_id FOREIGN KEY (provenance_id) REFERENCES "Project"(project_id) ON DELETE RESTRICT,
    CONSTRAINT fk_artifact_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_artifact_relevance_status ON "Artifact" (relevance_status);
CREATE INDEX IF NOT EXISTS idx_artifact_provenance_id ON "Artifact" (provenance_id);
CREATE INDEX IF NOT EXISTS idx_artifact_agent_id ON "Artifact" (agent_id);
