-- Elevated entity: Milestone
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)

CREATE TABLE IF NOT EXISTS "Milestone" (
    milestone_id        INT GENERATED BY DEFAULT AS IDENTITY,
    tracking_status     VARCHAR(32) NOT NULL,
    relevance_status    VARCHAR(32) NOT NULL,
    provenance_id       INT NOT NULL,
    agent_id            INT NOT NULL,
    title               VARCHAR(255) NOT NULL DEFAULT '',
    content             TEXT NOT NULL DEFAULT '',
    reason              VARCHAR(255) NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_milestone PRIMARY KEY (milestone_id),
    CONSTRAINT fk_milestone_tracking_status FOREIGN KEY (tracking_status) REFERENCES "TrackingStatus"(tracking_status) ON DELETE RESTRICT,
    CONSTRAINT fk_milestone_relevance_status FOREIGN KEY (relevance_status) REFERENCES "RelevanceStatus"(relevance_status) ON DELETE RESTRICT,
    CONSTRAINT fk_milestone_provenance_id FOREIGN KEY (provenance_id) REFERENCES "Project"(project_id) ON DELETE RESTRICT,
    CONSTRAINT fk_milestone_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_milestone_tracking_status ON "Milestone" (tracking_status);
CREATE INDEX IF NOT EXISTS idx_milestone_relevance_status ON "Milestone" (relevance_status);
CREATE INDEX IF NOT EXISTS idx_milestone_provenance_id ON "Milestone" (provenance_id);
CREATE INDEX IF NOT EXISTS idx_milestone_agent_id ON "Milestone" (agent_id);
