-- Elevated entity: StateTransition
-- Source: tmp/llm-memory-db.pseudo  (INDEPENDENT ENTITIES section)
--
-- Transitions are immutable: created_at + occurred_at only, no updated_at.
-- from_status / to_status are intentionally NOT FK-constrained — the discriminator
-- (state_transition_type) decides which reference table they belong to;
-- the proc layer enforces validity per discriminator.

CREATE TABLE IF NOT EXISTS "StateTransition" (
    transition_id           INT GENERATED BY DEFAULT AS IDENTITY,
    state_transition_type   VARCHAR(32) NOT NULL,
    agent_id                INT NOT NULL,
    from_status             VARCHAR(32) NOT NULL,
    to_status               VARCHAR(32) NOT NULL,
    reason                  VARCHAR(255) NOT NULL DEFAULT '',
    occurred_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_statetransition PRIMARY KEY (transition_id),
    CONSTRAINT fk_statetransition_state_transition_type FOREIGN KEY (state_transition_type) REFERENCES "StateTransitionType"(state_transition_type) ON DELETE RESTRICT,
    CONSTRAINT fk_statetransition_agent_id FOREIGN KEY (agent_id) REFERENCES "Agent"(agent_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_statetransition_state_transition_type ON "StateTransition" (state_transition_type);
CREATE INDEX IF NOT EXISTS idx_statetransition_agent_id ON "StateTransition" (agent_id);
CREATE INDEX IF NOT EXISTS idx_statetransition_occurred_at ON "StateTransition" (occurred_at);
