import type { Generated } from 'kysely';

/**
 * Row shape for the `Memory` table.
 *
 * A Memory is a single piece of recorded knowledge — a decision, fact,
 * gotcha, etc. — scoped to a `domain` + `category` and attributed to
 * the `agent_id` that recorded it. The four `was_*` booleans are
 * verifiable confidence claims combined by `fn_MemoryConfidence` into
 * the 0-4 score surfaced on `vw_Memory`.
 *
 * Columns wrapped with `Generated<T>` are filled by Postgres
 * (`GENERATED BY DEFAULT AS IDENTITY`, `DEFAULT NOW()`, `DEFAULT 0`,
 * `DEFAULT false`) — Kysely lets callers omit them on insert. The
 * defaults match the contract of `sp_Memory_Create`, which sets
 * `relevance_status = 'active'`, `last_accessed_at = now`,
 * `access_count = 0`, and the four `was_*` flags to `false` unless
 * the caller explicitly opts in.
 *
 * @example
 * ```typescript
 * const row = await ctx.kysely
 *     .selectFrom('Memory')
 *     .selectAll()
 *     .where('memory_id', '=', 42)
 *     .executeTakeFirst();
 * ```
 */
export interface MemoryRow {
    memory_id:         Generated<number>;
    domain:            string;
    category:          string;
    relevance_status:  Generated<string>;
    provenance_id:     number;
    agent_id:          number;
    content:           string;
    reason:            string;
    was_inferred:      Generated<boolean>;
    was_observed:      Generated<boolean>;
    was_evidenced:     Generated<boolean>;
    was_user_provided: Generated<boolean>;
    last_accessed_at:  Generated<Date>;
    access_count:      Generated<number>;
    created_at:        Generated<Date>;
    updated_at:        Generated<Date>;
}

/**
 * Stored-procedure contract for the `Memory` domain.
 *
 * Each entry is an `[args, result]` tuple. Arg keys use snake_case to
 * mirror the Postgres parameter names (with the `p_` prefix dropped) —
 * the camelCase to snake_case mapping happens inside `MemoryCommands`.
 *
 * - `sp_Memory_Create` returns the new `memory_id`.
 * - All other procs return `void`; they either succeed or raise.
 *
 * State transitions (`SetRelevance`, `Delete`, `Restore`) are gated by
 * `fn_IsRelevanceTransitionAllowed` in SQL — invalid `(from, to)`
 * pairs are rejected before any update.
 *
 * Attach / Detach / Relate / Unrelate procs are idempotent at the SQL
 * level (`ON CONFLICT DO NOTHING` / plain DELETE) — callers do not
 * need to wrap them in duplicate-key handling.
 *
 * @example
 * ```typescript
 * const { memory_id } = await ctx.proc('sp_Memory_Create', {
 *     content: 'kysely returns Generated<T> for defaults',
 *     domain: 'backend',
 *     category: 'fact',
 *     reason: 'observed while authoring memory domain',
 *     provenance_id: 0,
 *     agent_id: 0,
 *     was_inferred: false,
 *     was_observed: true,
 *     was_evidenced: true,
 *     was_user_provided: false,
 * });
 * ```
 */
export interface MemoryProcs {
    'sp_Memory_Create': [
        {
            p_content: string;
            p_domain: string;
            p_category: string;
            p_reason: string;
            p_provenance_id: number;
            p_agent_id: number;
            p_was_inferred: boolean;
            p_was_observed: boolean;
            p_was_evidenced: boolean;
            p_was_user_provided: boolean;
        },
        { memory_id: number },
    ];
    'sp_Memory_Update': [
        {
            p_memory_id: number;
            p_content: string;
            p_domain: string;
            p_category: string;
            p_reason: string;
            p_was_inferred: boolean;
            p_was_observed: boolean;
            p_was_evidenced: boolean;
            p_was_user_provided: boolean;
        },
        void,
    ];
    'sp_Memory_SetRelevance': [
        {
            p_memory_id: number;
            p_new_relevance_status: string;
            p_agent_id: number;
            p_reason: string;
        },
        void,
    ];
    'sp_Memory_Delete': [
        {
            p_memory_id: number;
            p_agent_id: number;
            p_reason: string;
        },
        void,
    ];
    'sp_Memory_Restore': [
        {
            p_memory_id: number;
            p_agent_id: number;
            p_reason: string;
        },
        void,
    ];
    'sp_Memory_Touch': [
        {
            p_memory_id: number;
            p_agent_id: number;
        },
        void,
    ];
    'sp_Memory_Relate': [
        {
            p_memory_id: number;
            p_related_memory_id: number;
            p_relation_verb: string;
            p_reason: string;
        },
        void,
    ];
    'sp_Memory_Unrelate': [
        {
            p_memory_id: number;
            p_related_memory_id: number;
        },
        void,
    ];
    'sp_Memory_Consolidate': [
        {
            p_canonical_memory_id: number;
            p_duplicate_memory_id: number;
            p_agent_id: number;
            p_reason: string;
        },
        void,
    ];
    'sp_Memory_Attach_Project': [
        {
            p_memory_id: number;
            p_project_id: number;
        },
        void,
    ];
    'sp_Memory_Detach_Project': [
        {
            p_memory_id: number;
            p_project_id: number;
        },
        void,
    ];
}

/**
 * Scalar function contract for the `Memory` domain.
 *
 * Both functions take a `memory_id` and return a single scalar wrapped
 * in `{ <alias>: T }` — the alias matches the third argument passed
 * to `ctx.func('fn_*', args, '<alias>')`.
 *
 * - `fn_MemoryConfidence` returns the count of `was_*` booleans set
 *   on the row (0-4).
 * - `fn_MemoryRank` returns the composite retrieval score combining
 *   confidence, recency decay, and a relevance-status weight.
 *
 * @example
 * ```typescript
 * const { confidence } = await ctx.func('fn_MemoryConfidence', { memory_id: 42 }, 'confidence');
 * const { rank }       = await ctx.func('fn_MemoryRank',       { memory_id: 42 }, 'rank');
 * ```
 */
export interface MemoryFuncs {
    'fn_MemoryConfidence': [
        { p_memory_id: number },
        { confidence: number },
    ];
    'fn_MemoryRank': [
        { p_memory_id: number },
        { rank: number },
    ];
    'fn_IsTrackingTransitionAllowed': [
        { p_from_status: string; p_to_status: string },
        { allowed: boolean },
    ];
    'fn_IsRelevanceTransitionAllowed': [
        { p_from_status: string; p_to_status: string },
        { allowed: boolean },
    ];
}
